version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend/Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - sqlite_data:/app/sqlite
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL_FOOD=http://backend:5000/api/food
        - REACT_APP_API_URL_SCRAPER=http://backend:5000/api/scraper/update-foods
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend

volumes:
  sqlite_data:
    name: sqlite_data
    driver: local
